version: "2"
services:
 chatbot:
    build:
      context: ""
      dockerfile: ./Dockerfile.centos
    image: chatbot:latest
    network_mode: bridge
    entrypoint:
      - /bin/entrypoint.sh
    environment:
      SERVICE_PORT: "6006"
      SERVICE_TIMEOUT: "900"
      WORKER_COUNT: "5"
      AWS_S3_ACCESS_KEY_ID : "AS"
      AWS_S3_SECRET_ACCESS_KEY : "/zIJPh0tKM7Kc"
      AWS_BUCKET_NAME : "imdb-movie-bucket"
      MOVIE_COUNT : 20
    ports:
      - "6006:6006"
